### ISSUE TITLE
How to start the gray duck on desired port?

### ISSUE THREAD

**Issue by robert-winkler** [wagesj45/gray-duck-mail#1]
Hi Jordan,
An easy-to-install mailing list platform is really much needed!
Thank you very much for your work!
I pulled the docker image.
Now, how do I run the server? 
I would like to use port 5000 (i.e. mydomain.org:5000) since I'm also running other stuff on this server.

**Comment by robert-winkler** [comment]
Found the solution:

~~~
root@localhost:~# docker run --name mydomain.com -d  -p 5000:80 wagesj45/gray-duck-mail 
root@localhost:~# docker container ls
CONTAINER ID   IMAGE                     COMMAND                  CREATED         STATUS         PORTS                                   NAMES
45f826bc4695   wagesj45/gray-duck-mail   "dotnet gray-duck-ma…"   5 minutes ago   Up 5 minutes   0.0.0.0:5000->80/tcp, :::5000->80/tcp   mydomain.com
~~~

Thanks a lot again for your great contribution!!

**Comment by wagesj45** [comment]
@robert-winkler I'm glad you found the solution. I will close the issue. Don't forget to check out the [getting started](http://grayduckmail.com/getting-started.html) page and review the [special security considerations](http://grayduckmail.com/security.html) for operating your server.
