### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pztrn** [wagesj45/gray-duck-mail#2]
Two words describing whole situation.

Using mailcow dockerized and latest docker image.

1. Can't subscribe via subscribe alias:

```
gdm_1  | [GrayDuckMail.Web.Worker.EmailFetcher] Recieved an unsolicited subscription confirmation from pztrn@pztrn.name for test-internal.
gdm_1  | [GrayDuckMail.Web.Worker.EmailFetcher] Message A369FC39-B05D-4D38-B923-A40F549BF267@pztrn.name (Index 0) processed. Marked for deletion from the server.
```

Nothing happens - no confirmation, no new contact, nothing.

2. Can't add contact manually via web ui. Always getting message:

>  There are some invitations still processing. Your server is configured to process new subscribers every 0.5 minutes. Please be patient.

Same as subscribing via alias - nothing happens.

**Comment by pztrn** [comment]
Okay, no. 1 is not valid - wrong alias, I should use `request-` one. Yet second one is valid and starts to work only after restarting an application.

Also, after I `request-`'d myself, I can't send mails to mailing list:

```
gdm_1  | [GrayDuckMail.Web.Worker.EmailFetcher] Filtering 1 messages.
```

And nothing appears in archive.

**Comment by wagesj45** [comment]
The `request-` alias should create the user in the system (if they're not already there) and then mark the user as inactive pending admin approval. Check the admin web interface for that subscription list and that user should be listed, allowing you to activate that user which allows them to send/receive messages.

Is this what you're seeing?

**Comment by wagesj45** [comment]
No response yet, so I'll mark this as closed.
