### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by es86de** [wagesj45/gray-duck-mail#6]
In my community, English language would very likely be a show stopper. Therefore, I would be willing to translate the auto-generated texts, like the unsubscribe line etc., to German. Would you be interested to add language support?

**Comment by wagesj45** [comment]
I'd be happy to add language support. I have a system coded from another personal project I could integrate. It utilizes `*.resx` files. If this is something for which you would like to volunteer for your language, please let me know and I'll create a feature branch, implement the feature, and tag you when I'm ready to accept a pull request on the appropriate language file.

**Comment by es86de** [comment]
Sounds great. Let's do it. :-)

**Comment by wagesj45** [comment]
Just a quick update: I've localized a large portion of the app, including almost all of the logging and backend system. The holiday slowed things down, but I'm still working on the localization of the front end (administration web pages). Thanks for your patience!

**Comment by wagesj45** [comment]
@es86de I have completed the localization support. You can check /gray-duck-mail/gray-duck-mail-common/Localization/Resources.de-DE.resx to see an automated translation. This is the file that will be utilized when setting the `LANGUAGE` docker environment variable to `de-DE`. Feel free to make any corrections to make it more human friendly, and submit a pull request.

**Comment by es86de** [comment]
Great work! I just submitted the PR.

I wanted to check the automated translation using the docker image, but the localization feature does not seem to be populated yet.

**Comment by wagesj45** [comment]
@es86de I just pushed the translations to both the `testing` and `latest` docker images. I usually use the `testing` image as a mid-development tool, and post to `latest` when I finalize the feature. Regardless, both images are now up-to-date and you are free to test the latest translation feature in either.
